UPDATED: Workflow v1

diff --git a/.github/workflows/myWorkflow.yaml b/.github/workflows/myWorkflow.yaml
--- a/.github/workflows/myWorkflow.yaml
+++ b/.github/workflows/myWorkflow.yaml
@@ -23,16 +23,24 @@ jobs:
           severity: 'HIGH'
           output: 'trivy-scan.txt'
 
-      - name: Vulnerabilities count         
-        run: echo "Vulnerabilities ${{ steps.trivy.outputs.vuln_count }}"
+      - name: Echo contents of trivy-scan.txt
+        run: |
+            if test -f trivy-scan.txt; then
+                cat trivy-scan.txt
+            else
+                echo "trivy-scan.txt does not exist."
+                exit 1
+            fi
 
-      - name: Vulnerabilities found
-         if ${{ steps.trivy.outputs.vuln_count > 0}}
-        run: echo "Vulnerabilities found"
+      - name: Slack Notification
+        uses: rtCamp/action-slack-notify@v2
+        env:
+          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
 
-      - name: Vulnerabilities found
-         if ${{ !steps.trivy.outputs.vuln_count > 0}}
-        run: echo "No vulnerabilities"
+
+
+
+
 
         #- name: Upload report
         #if: ${{ steps.trivy.outputs.exit_code == 1 }} 
